version: '3'
services:
  music-visualizer:
    build:
      context: ./
      args:
        - NO_CACHE=--no-cache
    image: music-visualizer:0.0.1
    volumes:
      - "/home/${USER}/Music:/visualizer/Music"
    devices:
      - /dev/snd
    stdin_open: true
    command: ["bash", "-it"]
    tty: true
    restart: "no"

