version: '3'
services:
  visualizer-service:
    build:
      context: ./
      args:
        - NO_CACHE=--no-cache
    image: music-visualizer:0.0.1
    container_name: visualizer-container
    volumes:
      - "${ENV_MUSIC_PATH}:/opt/visualizer/Music"
    devices:
      - /dev/snd
    stdin_open: true
    command: /bin/bash
    tty: true
    restart: "no"

